### PR TITLE
Added patch functionality.

### PR DESCRIPTION
**Pull request by ibnuda**
Added patch functionality. Though there are a few changes.

- Can't abstract `patch<'a>` function. (I still don't understand `Quotations`.)
- Have to install plv8 extension on Postgres for testing purpose. See [this](https://stackoverflow.com/questions/11584749/how-to-create-a-new-database-with-the-hstore-extension-already-installed) SO thread.

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Awesome!  I'll look at it tonight.

**Comment by TheAngryByrd** [comment]
We can probably borrow what Marten proper is doing to setup plv8 on the CI.

* https://github.com/JasperFx/marten/blob/master/.travis.yml
* https://github.com/JasperFx/marten/blob/master/appveyor.yml

**Comment by TheAngryByrd** [comment]
I think you need to add a generic type to the patch function

```Fsharp
    let patch<'a,'b> (id : Guid) (part : Quotations.Expr<'a -> 'b>) (newVal : 'b) (session : IDocumentSession) =
        let func = Lambda.ofArity1 part
        session.Patch<'a>(id).Set<'b>(func, newVal)
```

**Comment by ibnuda** [comment]
Sorry for the unnecessary commits. I didn't have any experience with CI before.

**Comment by TheAngryByrd** [comment]
No worries, I don't know of a better way to test it either.

Thanks a lot!

**Comment by TheAngryByrd** [comment]
Also should be on nuget now.  Might not be index yet tho. https://www.nuget.org/packages/Marten.FSharp/0.1.0-alpha005

**Pull request merged**
